version: "3"
services:
  app:
    build: .
    ports:
      - 8080:80
    restart: always
    volumes:
      - .:/var/www/html
    links:
      - db
  db:
    image: postgres:12.1
    ports: 
      - 33060:3306
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=pasha
      - POSTGRES_DB=docker_test
  adminer:
    image: adminer:4.7.5
    ports: 
      - 8081:8080
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
